CREATE TABLE ALUMNOS(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(50),
    APP NVARCHAR2 (50),
    MATRICULA NVARCHAR2 (50)
);

CREATE TABLE PROFESORES(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(50),
    APP NVARCHAR2 (50),
    MATRICULA NVARCHAR2 (50)
);

CREATE TABLE CLASES(
    --ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(50),
    ID_ALUMNO NUMBER,
    ID_PROFESOR NUMBER,
    CONSTRAINT FK_CLASE_ALUMNO FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNOS (ID),
    CONSTRAINT FK_CLASE_PROFESOR FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESORES (ID),
    PRIMARY KEY (ID_ALUMNO, ID_PROFESOR)
);
DROP TABLE CLASES;
INSERT INTO ALUMNOS VALUES (1, 'MARIO', 'GOMEZ', 'A01');
INSERT INTO PROFESORES VALUES (1, 'GERARDO', 'ROSAS', 'P01');
INSERT INTO CLASES VALUES('PROGRAMACION', 1, 1);

SELECT * FROM CLASES 
INNER JOIN ALUMNOS ON ALUMNOS.ID = CLASES.ID_ALUMNO
INNER JOIN PROFESORES ON PROFESORES.ID = CLASES.ID_PROFESOR;

COMMIT;