CREATE TABLE CELULAR(
    ID NUMBER PRIMARY KEY,
    MODELO NVARCHAR2(50),
    MARCA NVARCHAR2(50),
    PRECIO NUMBER
);

INSERT INTO CELULAR VALUES(1, 'MOTO ONE', 'MOTOROLA', 4500);
COMMIT;
SELECT * FROM  CELULAR;

DROP TABLE CELULAR31;

CREATE TABLE MARCACELULAR(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2 (50),
    PAIS NVARCHAR2 (15),
    SLOGAN NVARCHAR2 (50)
);

INSERT INTO MARCACELULAR VALUES(1, 'HUAWEI', 'CHINA', 'SALOGAN HUAWEI');
COMMIT;
SELECT * FROM MARCACELULAR;

CREATE TABLE DUENOPOKEMON(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(30),
    APP NVARCHAR2(30), 
    PUEBLO NVARCHAR2(30)
);

INSERT INTO DUENOPOKEMON VALUES (1, 'ASH', 'KETCHUP', 'PALETA');
COMMIT;
SELECT * FROM DUENOPOKEMON;

CREATE TABLE POKEMON(
    ID_P NUMBER PRIMARY KEY,
    NOMBRE_P NVARCHAR2(20),
    TIPO NVARCHAR2(10),
    ATAQUE NVARCHAR2(10),
    ID_DUENO NUMBER,
    CONSTRAINT FK_POKEMON_DUENO FOREIGN KEY (ID_DUENO) REFERENCES DUENOPOKEMON(ID)
);

INSERT INTO POKEMON VALUES(1, 'CHARMANDER', 'FUEGO', 'ASCUAS', 1);
COMMIT;
SELECT * FROM POKEMON;
DROP TABLE POKEMON;