CREATE TABLE EQUIPOSFUT(
    ID NUMBER,
    NOMBRE NVARCHAR2(50),
    PAIS NVARCHAR2(50),
    LIGA NVARCHAR2(50),
    TROFEOS NUMBER
);

INSERT INTO EQUIPOSFUT VALUES(1,'BARCELONA', 'ESPAÑA', 'LIGA ESPAÑOLA', 30);
COMMIT;