CREATE TABLE PAIS(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(50),
    CONTINENTE NVARCHAR2(50)
);

CREATE TABLE ESTADO(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(50),
    HABITANTES NUMBER,
    ID_PAIS NUMBER,
    CONSTRAINT FK_ES_PAIS FOREIGN KEY(ID_PAIS) REFERENCES PAIS
);

DROP TABLE ESTADO;
INSERT INTO PAIS VALUES(1, 'MEXICO', 'AMERICA');
INSERT INTO ESTADO VALUES(1, 'PUEBLA', 330000, 1);

COMMIT;