CREATE TABLE ZAPATO(
    ID NUMBER PRIMARY KEY,
    MODELO NVARCHAR2(30),
    TALLA NUMBER,
    MARCA NUMBER,
    COLOR NUMBER,
    PRECIO NUMBER,
    TIPO NUMBER
);
-- MARCA= 1=HUSHPUPPI, 2=NIKE, 3=ADIDAS, 4=TOMMY HILFIGER
-- COLOR 1=NEGRO, 2=BLANCO, 3=CAFE, 4=AZUL
-- TIPO 1=FORMAL, 2=DEPORTIVO, 3=CASUAL
INSERT INTO ZAPATO VALUES(1, 'ZP01', 9, 1, 1, 800, 1);
INSERT INTO ZAPATO VALUES(2, 'ZP02', 8, 2, 2, 900, 2);
INSERT INTO ZAPATO VALUES(3, 'RP01', 7, 3, 2, 700, 3);
INSERT INTO ZAPATO VALUES(4, 'RP02', 6, 4, 3, 640, 3);
INSERT INTO ZAPATO VALUES(5, 'RP03', 9, 2, 4, 810, 2);

--1.- MOSTRAR LOS DETALLES DE MARCA, COLOR, TIPO.
    SELECT ID, MODELO, TALLA,
    (
        CASE MARCA
        WHEN 1 THEN 'HUSHPUPPI'
        WHEN 2 THEN 'NIKE'
        WHEN 3 THEN 'ADIDAS'
        WHEN 4 THEN 'TOMMY HILFIGER'
        ELSE 'NO ESTA'
        END
    ) AS MARCA,
    (
        CASE COLOR
        WHEN 1 THEN 'NEGRO'
        WHEN 2 THEN 'BLANCO'
        WHEN 3 THEN 'CAFE'
        WHEN 4 THEN 'AZUL'
        ELSE 'NO ESTA'
        END
    )AS COLOR,
    (
        CASE TIPO
        WHEN 1 THEN 'FORMAL'
        WHEN 2 THEN 'DEPORTIVO'
        WHEN 3 THEN 'CASUAL'
        ELSE 'NO ESTA'
        END
    )AS TIPO
    FROM ZAPATO;

--2.- BUSCAR LOS REGISTROS QUE SU COLOR SEA AZUL O NEGRO.
    SELECT ID, MODELO, TALLA,
    (
        CASE MARCA
        WHEN 1 THEN 'HUSHPUPPI'
        WHEN 2 THEN 'NIKE'
        WHEN 3 THEN 'ADIDAS'
        WHEN 4 THEN 'TOMMY HILFIGER'
        ELSE 'NO ESTA'
        END
    ),
    (
        CASE COLOR
        WHEN 1 THEN 'NEGRO'
        WHEN 2 THEN 'BLANCO'
        WHEN 3 THEN 'CAFE'
        WHEN 4 THEN 'AZUL'
        ELSE 'NO ESTA'
        END
    ),
    (
        CASE TIPO
        WHEN 1 THEN 'FORMAL'
        WHEN 2 THEN 'DEPORTIVO'
        WHEN 3 THEN 'CASUAL'
        ELSE 'NO ESTA'
        END
    )FROM ZAPATO WHERE COLOR IN (1,4);

--3.- BUSCAR EL ZAPATO MAS CARO .
SELECT ID, MODELO, TALLA,
(
    CASE MARCA
    WHEN 1 THEN 'HUSHPUPPI'
    WHEN 2 THEN 'NIKE'
    WHEN 3 THEN 'ADIDAS'
    WHEN 4 THEN 'TOMMY HILFIGER'
    ELSE 'NO ESTA'
    END
)AS MARCA,
(
    CASE COLOR
    WHEN 1 THEN 'NEGRO'
    WHEN 2 THEN 'BLANCO'
    WHEN 3 THEN 'CAFE'
    WHEN 4 THEN 'AZUL'
    ELSE 'NO ESTA'
    END
)AS COLOR,
(
    CASE TIPO
    WHEN 1 THEN 'FORMAL'
    WHEN 2 THEN 'DEPORTIVO'
    WHEN 3 THEN 'CASUAL'
    ELSE 'NO ESTA'
    END
)AS TIPO, PRECIO, TIPO
FROM ZAPATO WHERE PRECIO = (SELECT MAX(PRECIO) ZAPATO_CARO FROM ZAPATO);

--4.- BUSCAR LOS ZAPATOS QUE SU MODELO SEA TIPO R.
SELECT ID, MODELO, TALLA,
(
    CASE MARCA
    WHEN 1 THEN 'HUSHPUPPI'
    WHEN 2 THEN 'NIKE'
    WHEN 3 THEN 'ADIDAS'
    WHEN 4 THEN 'TOMMY HILFIGER'
    ELSE 'NO ESTA'
    END
),
(
    CASE COLOR
    WHEN 1 THEN 'NEGRO'
    WHEN 2 THEN 'BLANCO'
    WHEN 3 THEN 'CAFE'
    WHEN 4 THEN 'AZUL'
    ELSE 'NO ESTA'
    END
),
(
    CASE TIPO
    WHEN 1 THEN 'FORMAL'
    WHEN 2 THEN 'DEPORTIVO'
    WHEN 3 THEN 'CASUAL'
    ELSE 'NO ESTA'
    END
)
FROM ZAPATO WHERE MODELO LIKE 'R%';

--5.- CONTAR CUANTOS ZAPATOS HAY DE CADA COLOR.
    SELECT 
    (
        CASE COLOR
        WHEN 1 THEN 'NEGRO'
        WHEN 2 THEN 'BLANCO'
        WHEN 3 THEN 'CAFE'
        WHEN 4 THEN 'AZUL'
        ELSE 'NO ESTA'
        END
    )AS COLOR,
    COUNT (COLOR) AS CANTIDAD
    FROM ZAPATO
    GROUP BY (COLOR);
