CREATE TABLE AVION(
    ID NUMBER PRIMARY KEY,
    MODELO NVARCHAR2(50),
    MARCA NVARCHAR2(50),
    PRECIO NUMBER
);

INSERT INTO AVION VALUES(1, 'BOEING', 'AMERICAN AIRLINES', 5000000);
COMMIT;

CREATE TABLE EMPRESAANGULAR(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(50),
    DIRECCION NVARCHAR2(50),
    CLAVE NVARCHAR2(50)
);

CREATE TABLE TELEVISIONANGULAR(
    ID NUMBER PRIMARY KEY,
    MODELO NVARCHAR2(50),
    MARCA NVARCHAR2(50),
    PRECIO NUMBER,
    ID_EMPRESA NUMBER,
    CONSTRAINT FK_TELE_EMPRESA FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAANGULAR(ID)
);

INSERT INTO EMPRESAANGULAR VALUES (1, 'E1', 'DIRECCION1', 'S001');
INSERT INTO EMPRESAANGULAR VALUES (2, 'E2', 'DIRECCION2', 'S002');
INSERT INTO EMPRESAANGULAR VALUES (3, 'E3', 'DIRECCION3', 'S003');

INSERT INTO TELEVISIONANGULAR VALUES (1, 'TV-001', 'SAMSUNG', 5000, 1);

COMMIT;

CREATE TABLE NOVIO (
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(50),
    APP NVARCHAR2(50),
    APM NVARCHAR2(50),
    PROFESION NVARCHAR2(50)
);

CREATE TABLE NOVIA(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(50),
    APP NVARCHAR2(50),
    APM NVARCHAR2(50),
    HOBBIE NVARCHAR2(50),
    ID_NOVIO NUMBER,
    FOREIGN KEY (ID_NOVIO) REFERENCES NOVIO (ID)
);

ALTER TABLE NOVIO
ADD ID_NOVIA NUMBER;

ALTER TABLE NOVIO
ADD CONSTRAINT FK_NOVIO_NOVIA FOREIGN KEY (ID_NOVIA) REFERENCES NOVIA(ID);

INSERT INTO NOVIO VALUES (1, 'GOKU', 'SON', 'CACAROTO', 'LUCHADOR', NULL);
INSERT INTO NOVIO VALUES (2, 'HOMERO', 'SIMPSON', 'MUT', 'INGENIERO', NULL);
INSERT INTO NOVIA VALUES (1, 'MILK', 'OCC', 'SATAN', 'COCINAR', 1);

UPDATE NOVIO SET ID_NOVIA = 1 WHERE ID = 1;

COMMIT;

SELECT * FROM NOVIO;