--                                 ->CHECK<-
CREATE TABLE LENTES(
    ID NUMBER PRIMARY KEY,
    MODELO NVARCHAR2(30),
    MARCA NUMBER,
    PRECIO NUMBER,
    TIPO NVARCHAR2(15),
    GRADUACION NUMBER,
    CONSTRAINT CHECK_LENTES_TIPO CHECK(TIPO IN ('SOL', 'EJECUTIVO', 'DEPORTIVO'))
);
--MARCA 1=HUGO, 2=RAYBAN,3=DORADA, 4=HILER, 5=PUSHER
--TIPO 1=SOL, 2=EJECUTIVO, 3=DEPORTIVO
INSERT INTO LENTES VALUES(1, 'M1', 1, 800, 'SOL', 3.5);
INSERT INTO LENTES VALUES(2, 'M2', 2, 1200, 'EJECUTIVO', 1.2);
INSERT INTO LENTES VALUES(3, 'R21', 2, 2200, 'DEPORTIVO', 1.9);
INSERT INTO LENTES VALUES(4, 'M25', 1, 3500, 'EJECUTIVO', 2.2);
INSERT INTO LENTES VALUES(5, 'R11', 3, 4000, 'DEPORTIVO', 3.1);




--MOSTRAR DETALLE DE LA MARCA
SELECT ID, MODELO,
(
    CASE MARCA
    WHEN 1 THEN 'HUGO'
    WHEN 2 THEN 'RAYBAN'
    WHEN 3 THEN 'DORADA'
    WHEN 4 THEN 'HILER'
    WHEN 5 THEN 'PUSHER'
    ELSE 'NO ESTA'
    END
) AS MARCA, PRECIO, TIPO, GRADUACION
FROM LENTES;

--BUSCAR LENTE MAS CARO
SELECT ID, MODELO,
(
    CASE MARCA
    WHEN 1 THEN 'HUGO'
    WHEN 2 THEN 'RAYBAN'
    WHEN 3 THEN 'DORADA'
    WHEN 4 THEN 'HILER'
    WHEN 5 THEN 'PUSHER'
    ELSE 'NO ESTA'
    END
) AS MARCA, PRECIO, TIPO, GRADUACION
FROM LENTES WHERE PRECIO = (SELECT MAX(PRECIO) AS PRECIO_MAYOR FROM LENTES);

--BUSCAR CON GRADUACION MAS BAJA
SELECT ID, MODELO,
(
    CASE MARCA
    WHEN 1 THEN 'HUGO'
    WHEN 2 THEN 'RAYBAN'
    WHEN 3 THEN 'DORADA'
    WHEN 4 THEN 'HILER'
    WHEN 5 THEN 'PUSHER'
    ELSE 'NO ESTA'
    END
) AS MARCA, PRECIO, TIPO, GRADUACION
FROM LENTES WHERE GRADUACION = (SELECT MIN(GRADUACION) AS GRADUACION_MENOR FROM LENTES);

--CONTAR CUANTOS LENTES HAY DE CADA MARCA
    SELECT
    (
        CASE MARCA
        WHEN 1 THEN 'HUGO'
        WHEN 2 THEN 'RAYBAN'
        WHEN 3 THEN 'DORADA'
        WHEN 4 THEN 'HILER'
        WHEN 5 THEN 'PUSHER'
        ELSE 'NO ESTA'
        END
    ) AS MARCA,
    COUNT (MARCA) AS CANTIDAD
    FROM LENTES
    GROUP BY(MARCA);

--MOSTRAR REGISTROS ORDENADOS EN BASE A SU PRECIO -> MOSTRAR SI EL PRECIO ES MENOR DE 1000 = "BARATO"
--  SI ESTÁ ENTRE 1001 Y 2500 REGULAR Y SI ES MAS DE 2501 CARO
SELECT ID, MODELO,
    (
        CASE MARCA
        WHEN 1 THEN 'HUGO'
        WHEN 2 THEN 'RAYBAN'
        WHEN 3 THEN 'DORADA'
        WHEN 4 THEN 'HILER'
        WHEN 5 THEN 'PUSHER'
        ELSE 'NO ESTA'
        END
    ) AS MARCA, PRECIO,
    (
        CASE 
        WHEN PRECIO <1000 THEN 'BARAT0'
        WHEN PRECIO >=1001 AND PRECIO <=2500 THEN 'REGULAR'
        WHEN PRECIO >= 2501 THEN 'CARO'
        ELSE 'NO ESTA'
        END
    ) AS CARO_BARATO, TIPO, GRADUACION
FROM LENTES
ORDER BY PRECIO DESC;
