CREATE TABLE ANIMALANGULAR(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(50),
    EDAD NUMBER,
    TIPO NVARCHAR2(50)
);

INSERT INTO ANIMALANGULAR VALUES (1, 'TOBY', 12, 'PERRO');
SELECT * FROM ANIMALANGULAR;
COMMIT;