CREATE TABLE PLAYERA(
    ID NUMBER PRIMARY KEY,
    MODELO NVARCHAR2(50),
    MARCA NVARCHAR2(50),
    TALLA NUMBER,
    PRECIO NUMBER
);

INSERT INTO PLAYERA VALUES(1, 'M1', 'NIKE', 30, 300);
INSERT INTO PLAYERA VALUES(2, 'M2', 'ADIDAS', 35, 400);
INSERT INTO PLAYERA VALUES(3, 'M3', 'REBOOK', 32, 500);
INSERT INTO PLAYERA VALUES(4, 'M4', 'ADIDAS', 28, 300);
INSERT INTO PLAYERA VALUES(5, 'M5', 'NIKE', 29, 450);
INSERT INTO PLAYERA VALUES(6, 'S1', 'NIKE', 30.5, 700);
INSERT INTO PLAYERA VALUES(7, 'S2', 'NIKE', 31, 800);
INSERT INTO PLAYERA VALUES(8, 'S3', 'ADIDAS', 28, 320);
INSERT INTO PLAYERA VALUES(9, 'S4', 'REBOOK', 26, 400);
INSERT INTO PLAYERA VALUES(10, 'S5', 'NULL', 28.5, 299);

SELECT * FROM PLAYERA;

--1.- MOSTAR REGISTROS ORDENADOS DEL MAS CARO AL MAS BARATO Y EL CAMPO PRECIO CONCATENAR "$"
SELECT ID, MODELO, MARCA, TALLA, CONCAT('$',PRECIO) AS PRECIO
FROM PLAYERA
ORDER BY PRECIO DESC;

--2.- MOSTRAR EL REGISTRO MAS CARO (SUBCONSULTA)
SELECT * FROM PLAYERA WHERE PRECIO = (SELECT MAX(PRECIO) MAX_GANANCIA FROM PLAYERA);

--3.- MOSTRAR CUANTAS PLAYER M2 HAY
SELECT COUNT(MODELO) AS CANTIDAD FROM PLAYERA WHERE MODELO ='M2';

--4.- OBTENER LA MEDIA DE PRECIO DE LA MARCA NIKE Y ADIDAS
SELECT AVG(PRECIO) AS PROMEDIO FROM PLAYERA WHERE MARCA = 'NIKE' OR MARCA = 'ADIDAS';

--5.- CONTAR CUANTAS PLAYERAS HAY DE CADA MARCA
 