CREATE TABLE GATO(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(20),
    GENERO NVARCHAR2(10),
    EDAD NUMBER
);

INSERT INTO GATO VALUES(1, 'DON GATO', 'MACHO', 5);
COMMIT;
SELECT * FROM GATO;

CREATE TABLE TANQUE(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(30),
    PAIS NVARCHAR2(30),
    DANO NUMBER,
    HP NUMBER
);

INSERT INTO TANQUE VALUES(1, 'MS-1', 'RUSIA', 500, 10000);
COMMIT;
SELECT * FROM TANQUE;
