--MARCA 1=USA, 2=TAIWAN, 3=JAPON, 4=CHINA, 5=KOREA, 6=MEXICO
CREATE TABLE MARCA_T(
    ID NUMBER PRIMARY KEY,
    NOMBRE NVARCHAR2(50),
    PAIS NUMBER,
    SLOGAN NVARCHAR2(50)
);  

CREATE TABLE TELEVISION_T(
    ID NUMBER PRIMARY KEY,
    MODELO NVARCHAR2(50),
    PRECIO NUMBER,
    PULGADAS NUMBER,
    ID_MARCA NUMBER,
    --CONSTRAINT FK_TV_MARCA_T FOREIGN KEY(ID_MARCA) REFERENCES MARCA_T(ID)
    FOREIGN KEY(ID_MARCA) REFERENCES MARCA_T(ID)
); 

INSERT INTO MARCA_T VALUES(1, 'LG', 5, 'LA VIDA ES BELLA');
INSERT INTO MARCA_T VALUES(2, 'SAMSUNG', 5, 'ESTAN PADRE');
INSERT INTO MARCA_T VALUES(3, 'PANASONIC', 1, 'LA VIDA SIGUE');
INSERT INTO MARCA_T VALUES(4, 'SONY', 4, 'EL ERROR');

INSERT INTO TELEVISION_T VALUES(1, 'T-01', 10000, 55, 1);
INSERT INTO TELEVISION_T VALUES(2, 'T-02', 20000, 50, 2);
INSERT INTO TELEVISION_T VALUES(3, 'T-03', 12000, 30, 3);
INSERT INTO TELEVISION_T VALUES(4, 'T-04', 15000, 65, 4);
INSERT INTO TELEVISION_T VALUES(5, 'T-05', 13000, 60, 2);
INSERT INTO TELEVISION_T VALUES(6, 'T-01', 8000, 30, NULL);


--1 MOSTRAR LAS TELEVICIONES CON SU MARCA Y LA MARCA MOSTRAR EL DETALLE DE SU PAIS.
SELECT T.ID, T.MODELO, T.PRECIO, T.PULGADAS,
    M.ID, M.NOMBRE,
    (
        CASE M.PAIS
        WHEN 1 THEN 'USA'
        WHEN 2 THEN 'TAIWAN'
        WHEN 3 THEN 'JAPON'
        WHEN 4 THEN 'CHINA'
        WHEN 5 THEN 'KOREA'
        WHEN 6 THEN 'MEXICO'
        ELSE 'NO ESTA'
        END
    ) AS PAIS, M.SLOGAN
FROM TELEVISION_T T
INNER JOIN MARCA_T M 
ON M.ID = T.ID_MARCA;

--2 BUSCAR LA TELEVICION CON LAS PULGADAS MAS CARAS
SELECT * FROM TELEVISION_T
INNER JOIN MARCA_T ON MARCA_T.ID = TELEVISION_T.ID_MARCA
WHERE PRECIO = (SELECT MAX(PRECIO) FROM TELEVISION_T);

--3 MOSTRAR LAS TELEVICIONES CON SU MARCA , SI NO TIENE MOSTRAR NULL
SELECT * FROM TELEVISION_T
LEFT JOIN MARCA_T ON MARCA_T.ID = TELEVISION_T.ID_MARCA

--4 ORDENAR LAS TELEVICIONES EN BASE A SU MARCA EN ORDEN ALFABETICO
SELECT * FROM TELEVISION_T
FULL JOIN MARCA_T ON MARCA_T.ID = TELEVISION_T.ID_MARCA
ORDER BY(MARCA_T.NOMBRE)

--5 BUSCAR LAS MARCAS QUE SEAN T-01 Y ORDNARLAS EN BASE A SU PRECIO, AGREGARLE AL PRECIO $
SELECT M.ID, M.NOMBRE, M.PAIS, M.SLOGAN,
    T.ID, T.MODELO, CONCAT ('$', T.PRECIO) AS PRECIO, T.PULGADAS
FROM TELEVISION_T T
FULL JOIN MARCA_T M
ON M.ID = T.ID_MARCA
WHERE T.MODELO = 'T-01'
ORDER BY (T.PRECIO);
